apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: coo9t7mha-python 
  janus-idp.io/tekton: coo9t7mha-python
  backstage.io/kubernetes-id: coo9t7mha-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: coo9t7mha-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml