apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: coo9t7mha-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: coo9t7mha-python 
  name: coo9t7mha-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: coo9t7mha-python 
